In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np
%matplotlib inline

Link the Fuzzy table to GPS file

In [2]:
GPS_939 = pd.read_csv('../Data/GPS/2022/CSV/939_cl_R.csv')
FZ_939 = pd.read_csv('../testFuzzy/Fuzzy_table/Output_939_2.csv', header = None)
df_939 = pd.merge(GPS_939, FZ_939, left_on='No', right_on= 3, how='inner')
df_939.head()

,FID,GMT_Time,Latitude,Longitude,Altitude,Duration,Temperatur,DOP,Satellites,Cause_of_F,...,dt,speed,FM3_R,FM3_G,FM3_T,RASTERVALU,0,1,2,3
0,0,2022-10-15 15:50:00,36.186840,-109.906149,1989.69,31.0,18.5,2.4,5.0,GPS Schedule,...,0.0,0.000000,0.500000,0.0,0.0,0.272153,0.6,0.996746,0.301395,0
1,1,2022-10-15 16:00:00,36.186915,-109.906872,1998.64,1.0,22.5,2.6,5.0,GPS Schedule,...,10.0,0.000000,0.500000,0.0,0.0,0.264060,0.6,0.394965,0.559301,1
2,2,2022-10-15 16:10:00,36.188133,-109.907068,1993.42,2.0,24.5,2.6,5.0,GPS Schedule,...,10.0,10.090849,0.300000,0.0,0.0,0.265964,0.3,0.300000,0.335438,2
3,3,2022-10-15 16:20:00,36.188461,-109.907021,1994.45,9.0,27.0,2.4,5.0,GPS Schedule,...,10.0,8.642272,0.300000,0.0,0.0,0.266029,0.3,0.300000,0.300000,3
4,4,2022-10-15 16:30:00,36.188479,-109.906926,1981.54,4.0,28.0,2.0,5.0,GPS Schedule,...,10.0,2.270743,0.360424,0.0,0.0,0.266327,0.3,0.300000,0.315217,4

In [18]:
df_939['time'] = pd.to_datetime(df_939['time'])
df_939.set_index('time', inplace=True)
df_939 = df_939.between_time('7:00:00','20:00:00')
df_939 = df_939.reset_index()

oct_df = df_939[df_939['time'].dt.month == 10]
nov_df = df_939[df_939['time'].dt.month == 11]
dec_df = df_939[df_939['time'].dt.month == 12]
jan_df = df_939[df_939['time'].dt.month == 1]
feb_df = df_939[df_939['time'].dt.month == 2]
mar_df = df_939[df_939['time'].dt.month == 3]
apr_df = df_939[df_939['time'].dt.month == 4]
may_df = df_939[df_939['time'].dt.month == 5]
jun_df = df_939[df_939['time'].dt.month == 6]

In [4]:
combination = []
all_p = range(0,3**12)
for i2 in all_p:
    Tri = []
    Quotient = int(i2/3)
    Reminder = i2 % 3
    Tri.append(Reminder)
    while Quotient != 0:
        Reminder = Quotient % 3
        Tri.append(Reminder)
        Quotient = int(Quotient/3) 
    combination.append(Tri)
    #print (Tri)
#print (combination)

comb = []
for i in combination:
    j = i[:]
    l = len(j)
    while l != 16:
        j.append(0)
        l = l + 1
    comb.append(j)
    #print (j,j[0]*3**0 + j[1]*3**1 + j[2]*3**2 + j[3]*3**3 + j[4]*3**4 + j[5]*3**5
    #      + j[6]*3**6 + j[7]*3**7 + j[8]*3**8 + j[9]*3**9 + j[10]*3**10 + j[11]*3**11
    #      + j[12]*3**12 + j[13]*3**13 + j[14]*3**14)
#print (comb)

In [43]:
tmp_df = oct_df[oct_df['time'].dt.day == 16]
tmp_df[-10:]

,time,FID,GMT_Time,Latitude,Longitude,Altitude,Duration,Temperatur,DOP,Satellites,...,dt,speed,FM3_R,FM3_G,FM3_T,RASTERVALU,0,1,2,3
53,2022-10-16 12:30:00,105,2022-10-16 18:30:00,36.192453,-109.909696,1986.54,2.0,13.0,1.2,7.0,...,10.0,32.292233,0.3,0.0,0.0,0.268482,0.3,0.3,0.300333,105
54,2022-10-16 12:40:00,106,2022-10-16 18:40:00,36.193103,-109.914799,1989.66,3.0,13.0,1.2,6.0,...,10.0,41.979151,0.3,0.0,0.0,0.266946,0.3,0.3,0.305165,106
55,2022-10-16 12:50:00,107,2022-10-16 18:50:00,36.190300,-109.916902,1988.03,1.0,13.5,1.2,6.0,...,10.0,41.414090,0.3,0.0,0.0,0.263849,0.3,0.3,0.300873,107
56,2022-10-16 13:00:00,108,2022-10-16 19:00:00,36.186660,-109.919333,1988.27,4.0,13.0,1.4,6.0,...,10.0,41.154277,0.3,0.0,0.0,0.259624,0.3,0.3,0.300000,108
57,2022-10-16 14:00:00,109,2022-10-16 20:00:00,36.189450,-109.917282,1976.50,9.0,16.5,2.6,4.0,...,60.0,11.707142,0.3,0.0,0.0,0.263055,0.3,0.3,0.303091,109
58,2022-10-16 15:01:00,110,2022-10-16 21:01:00,36.199856,-109.914159,1993.11,65.0,17.5,1.2,6.0,...,61.0,12.796365,0.3,0.0,0.0,0.269488,0.3,0.3,0.300000,110
59,2022-10-16 16:00:00,111,2022-10-16 22:00:00,36.191120,-109.906276,1995.81,3.0,10.0,1.8,5.0,...,59.0,19.906291,0.3,0.0,0.0,0.268143,0.3,0.3,0.300000,111
60,2022-10-16 17:00:00,112,2022-10-16 23:00:00,36.184249,-109.906676,1991.65,5.0,10.5,3.0,4.0,...,60.0,16.501953,0.3,0.0,0.0,0.270284,0.3,0.3,0.300000,112
61,2022-10-16 18:00:00,113,2022-10-17 00:00:00,36.182792,-109.906052,1989.16,59.0,12.5,1.4,6.0,...,60.0,7.784641,0.3,0.0,0.0,0.269378,0.3,0.3,0.330380,113
62,2022-10-16 19:00:00,114,2022-10-17 01:00:00,36.186749,-109.906406,2008.54,1.0,14.0,1.2,6.0,...,60.0,5.093882,0.3,0.0,0.0,0.264019,0.3,0.3,0.329048,114

In [ ]:
for i in range(31):
    hourly_list = []
    try:
        tmp_df = oct_df[oct_df['time'].dt.day == i]
    except:
        continue
    for j in range(8,19):
        if tmp_df[tmp_df['time'].dt.hour == j].shape[0] > 0: # enough records in current hour
            hourly_list.append([tmp_df[tmp_df['time'].dt.hour == j].iloc[0][0], 
                                tmp_df[tmp_df['time'].dt.hour == j].iloc[0][1], 
                                tmp_df[tmp_df['time'].dt.hour == j].iloc[0][2],
                                tmp_df[tmp_df['time'].dt.hour == j].iloc[0]['RASTERVALU']])
            
        elif tmp_df[tmp_df['time'].dt.hour == j - 1].shape[0] > 0: # enough records in previous hour
            hourly_list.append([tmp_df[tmp_df['time'].dt.hour == j - 1].iloc[0][0], 
                                tmp_df[tmp_df['time'].dt.hour == j - 1].iloc[0][1], 
                                tmp_df[tmp_df['time'].dt.hour == j - 1].iloc[0][2],
                                tmp_df[tmp_df['time'].dt.hour == j - 1].iloc[0]['RASTERVALU']])
            
        elif tmp_df[tmp_df['time'].dt.hour == j + 1].shape[0] > 0: # enough records in post hour
            hourly_list.append([tmp_df[tmp_df['time'].dt.hour == j + 1].iloc[0][0], 
                                tmp_df[tmp_df['time'].dt.hour == j + 1].iloc[0][1], 
                                tmp_df[tmp_df['time'].dt.hour == j + 1].iloc[0][2],
                                tmp_df[tmp_df['time'].dt.hour == j + 1].iloc[0]['RASTERVALU']])
            
        else:
            not_enough_data = 1
            break

In [55]:
tmp_df[tmp_df['time'].dt.hour == 8].shape

(6, 27)